apiVersion: v1
kind: Secret
metadata:
  name: otter-post-db-credentials
type: Opaque
data:
  POSTGRES_DB: b3R0ZXJfcG9zdF9kYXRhYmFzZQ== # base64-encoded value of 'otter_post_database'
  POSTGRES_USER: cG9zdGdyZXM=                # base64-encoded value of 'postgres'
  POSTGRES_PASSWORD: MDcwNw==                     # base64-encoded value of '0707'