apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-microservice
  template:
    metadata:
      labels:
        app: post-microservice
    spec:
      containers:
      - name: post-microservice
        image: koost07/post-microservice:latest
        env:
        - name: USER_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: otter-post-db-credentials
              key: POSTGRES_USER
        - name: USER_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: otter-post-db-credentials
              key: POSTGRES_PASSWORD
        - name: HOST_IP_ADR
          value: "postgres-post"
        - name: DB_PORT
          value: "5432"
        - name: USER_DB_NAME
          valueFrom:
            secretKeyRef:
              name: otter-post-db-credentials
              key: POSTGRES_DB
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: post-microservice
spec:
  selector:
    app: post-microservice
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 5002
