apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-microservice
  template:
    metadata:
      labels:
        app: user-microservice
    spec:
      containers:
      - name: user-microservice
        image: user-microservice:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5001
